sonar.projectKey=rasagyavatsal_CropCheckUp
sonar.organization=rasagyavatsal
sonar.sources=cropcheckup.py
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py
sonar.exclusions=models/**
sonar.sourceEncoding=UTF-8
