sonar.projectKey=rasagyavatsal_CropCheckUp
sonar.organization=rasagyavatsal
sonar.sources=landing/src
sonar.tests=landing/tests
sonar.test.inclusions=landing/tests/**/*.ts
sonar.exclusions=landing/public/models/**,landing/dist/**
sonar.sourceEncoding=UTF-8
