name: crop_check_up
description: "CropCheckUp - AI-powered plant disease detection"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  tflite_flutter: ^0.11.0
  camera: ^0.11.1
  image: ^4.5.3
  path_provider: ^2.1.5
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  image_background_remover: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/plant_disease_model.tflite
    - assets/labels.txt
    - assets/disease_info.json
